//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace BankServiceConsumer.BankServiceWeb {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BankServiceSoap", Namespace="http://tempuri.org/")]
    public class BankService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public BankService() {
            this.Url = "http://localhost/BankService/BankService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransferirFondos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TransferirFondos(string NroCuentaOrigen, string NroCuentaDestino, System.Single Monto) {
            object[] results = this.Invoke("TransferirFondos", new object[] {
                        NroCuentaOrigen,
                        NroCuentaDestino,
                        Monto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTransferirFondos(string NroCuentaOrigen, string NroCuentaDestino, System.Single Monto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TransferirFondos", new object[] {
                        NroCuentaOrigen,
                        NroCuentaDestino,
                        Monto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndTransferirFondos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Depositar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Depositar(string NroCuenta, System.Single Monto) {
            object[] results = this.Invoke("Depositar", new object[] {
                        NroCuenta,
                        Monto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDepositar(string NroCuenta, System.Single Monto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Depositar", new object[] {
                        NroCuenta,
                        Monto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDepositar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Extraer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Extraer(string NroCuenta, System.Single Monto) {
            object[] results = this.Invoke("Extraer", new object[] {
                        NroCuenta,
                        Monto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExtraer(string NroCuenta, System.Single Monto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Extraer", new object[] {
                        NroCuenta,
                        Monto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndExtraer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerSaldo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerSaldo(string NroCuenta) {
            object[] results = this.Invoke("ObtenerSaldo", new object[] {
                        NroCuenta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerSaldo(string NroCuenta, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerSaldo", new object[] {
                        NroCuenta}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndObtenerSaldo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
